config/routes.rb
Rails.application.routes.draw do
  root to: 'casts#index'
  devise_for :users
  resources :users

  resources :casts
  get '/' => 'casts#index'
  get '/login' => 'casts#login'
  get '/castout/' => 'casts#castout'
  post '/submit' => 'casts#postcast'
  get '/submit' => 'casts#nth'
  get '/thanks' => 'casts#thanks'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  protect_from_forgery with: :null_session,
          if: Proc.new { |c| c.request.format =~ %r{application/json} }
end

app/controllers/casts_controller.rb
require 'koala'
require 'twitter'
require 'json'
require 'rest_client'
require 'json'
require 'date'

class CastsController < ApplicationController
  def index
    render 'welcome'
  end

  def postcast
    @title = params["title"]
    @day = params["date"]
    @time1 = params["time1"]
    @time2 = params["time2"]
    @events = find_events
    @places = get_venue
    @venue = @places.first["name"]
    @starttime = epochtime(params["date"], params["time1"])
    @endtime = epochtime(params["date"], params["time2"])
    @duration = @endtime.to_i - @starttime.to_i
    @desc = params["desc"]
    @msg = params["msg01"]
    @url = create_event(@starttime, @duration, @events.last, @desc , params["title"], @places.first)
    if params["checkbox-1"].eql? "on"
      post_facebook(fb_message)
    end
    if params["checkbox-2"].eql? "on"
      post_twitter(t_message)
    end
    render 'thanks'
  end

  def thanks
    render 'thanks'
  end

  def fb_message
    c =  <<EOF
    #{@title} by #{@events.last["name"]}
    ---------------------------------------------------
    #{@msg}
    #{@title}
    #{@day} From #{@time1} to #{@time2}
    Place: #{@venue}
    Description:
    #{@desc}
    ----------------------------------------------------
    Please sign up here
    #{@url}
EOF
    c
  end

  def t_message
    d =  <<EOF
    #{@title} by #{@events.last["name"]} on #{@day} from #{@time1} to #{@time2} @ #{@venue}. Please sign up here #{@url}
EOF
    d
  end

  def epochtime(date, time)
    datearray = date.split("-").map {|r| r.to_i}
    timearray = time.split(":").map {|r| r.to_i}
    DateTime.new(datearray[0],datearray[1],datearray[2],timearray[0],timearray[1],0,'-7').strftime('%Q')
  end

  def castout
    @events = find_events.map { |r| r["name"] }
    @places = get_venue.map { |r| r["name"] }
    render "post"
  end

  def find_events
    apikey = APP_CONFIG["MEETUP_API"]
    member_id = APP_CONFIG["MEETUP_MEMBERID"]
    url = "http://api.meetup.com/2/groups"
    res = JSON.parse(RestClient.get url, {:params => {
        :organizer_id => member_id,
        :key => apikey,
    }})
    res["results"]
  end

  def get_venue
    apikey = APP_CONFIG["MEETUP_API"]
    res = find_events
    url = "http://api.meetup.com/2/venues"
    res = JSON.parse(RestClient.get url, {:params => {
      :group_id => res.reverse.first["id"],
      :key => apikey,
    }})
    res["results"]
  end

  def create_event(starttime, duration, meetup_group, desc, name, place)
    apikey = APP_CONFIG["MEETUP_API"]
    url = "http://api.meetup.com/2/event"
    input = {
      :group_id => meetup_group["id"],
      :group_urlname => meetup_group["link"],
      :name => name,
      :key => apikey,
      :description => desc,
      :time => starttime,
      :duration => duration,
      :venue_id => place["id"].to_i,
    }
    puts input
    res = JSON.parse(RestClient.post url, input)
    res["event_url"]
  end

  def post_facebook(message)
    key =  APP_CONFIG["FACEBOOK_KEY"]
    @graph = Koala::Facebook::API.new(key)
    accounts = @graph.get_connections("me", "accounts")
    keypage = accounts.first["access_token"]
    pageid = accounts.first["id"]
    @graph = Koala::Facebook::API.new(keypage)
    @graph.put_object(pageid, "feed", :message => message)
  end

  def post_twitter(message)
    client = Twitter::REST::Client.new do |config|
      conkey = APP_CONFIG["TWITTER_CONKEY"]
      consec = APP_CONFIG["TWITTER_CONSEC"]
      acctoken  = APP_CONFIG["TWITTER_ACCESS"]
      accsec = APP_CONFIG["TWITTER_SEC"]
      config.consumer_key = conkey
      config.consumer_secret = consec
      config.access_token = acctoken
      config.access_token_secret = accsec
    end
    client.update(message)
  end

  def nth
    render 'thanks'
  end

  def login
    render 'index'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casts_helper.rb
module CastsHelper
end

app/views/casts/index.html.erb
<!doctype html>
<html lang="en" manifest="cache.manifest">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="description" content="Meetup Tweetbook">
<meta name="keywords" content="post meetup, tweet meetup, post on facebook, meetup on FB">
<title>Eventcast</title>




<link rel="stylesheet" href="http://code.jquery.com/mobile/1.1.1/
	jquery.mobile-1.1.1.min.css"/>
	<script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
	<script src="http://code.jquery.com/mobile/1.1.1/jquery.mobile-1.1.1.min.js"></script>


	<meta name="viewport" content="width-device-width,
	initial-scale=1, maximum-scale=1" />





<style>

.centerblock {
	position:absolute;
    width: 300px;}

div.ui-btn, input[type="submit"]
{
    text-decoration:none !important;
    font-family:helvetica !important;
    color:white !important;
	  text-shadow:0 0 0;
    background:red !important;
}
.ui-input-text
{
height: 25px !important;
}
textarea.ui-input-text
{
    height:100px !important;
}
</style>






</head>

<body>


<div data-role="page" class="wrapper" id="main">

	<header data-role="header">
	<p align="center"><b><font size="5"><image src="images/logo_j.jpg">
	Eventcast</font></b>
	<br>
    <font size="2">Post your Meetup to the World</font>
	</p>
	</header>





	<h2 style="text-align:center">Loggin</h2>

 <ul data-role="listview">
 <li>
 <p align="center">
 <form method="get" enctype="multipart/form-data"
 name="myemailform" action="/castout">
	<div class="center">
	<p>
		<H2><label for='name'>Username: </label></H2>
		<input type="text" name="name">
	<br>
		<H2><label for='pwd'>Password:</label></H2>
		<input type="text" name="pwd">
	</p>
	</div>
	<p>
	<input type="submit" name='submit' value="Submit">
</form>
 </p>
</li>
	</ul>
	  <div>
	  <footer data-role="footer">
	  <nav data-role="navbar">
	  <p align="center">
    <img border="0" src="images/loudspeakwave.gif">
	  <br>
	  </p>
	</footer>
	</div>


	</div>




</body>

</html>

app/views/casts/post.html.erb
<!doctype html>
<html lang="en" manifest="cache.manifest">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="description" content="Meetup Tweetbook">
<meta name="keywords" content="post meetup, tweet meetup, post on facebook, meetup on FB">
<title>Eventcast</title>
<script>
  //reset type=date inputs to text
  $( document ).bind( "mobileinit", function(){
    $.mobile.page.prototype.options.degradeInputs.date = true;
  });
</script>


<link rel="stylesheet" href="http://code.jquery.com/mobile/1.1.1/
	jquery.mobile-1.1.1.min.css"/>
	<script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
	<script src="http://code.jquery.com/mobile/1.1.1/jquery.mobile-1.1.1.min.js"></script>

	<meta name="viewport" content="width-device-width,
	initial-scale=1, maximum-scale=1" />
<style>
.centerblock {
	position:absolute;
    width: 300px;}

div.ui-btn, input[type="submit"]
{
  text-decoration:none !important;
  font-family:helvetica !important;
  color:white !important;
  text-shadow:0 0 0;
  background:red !important;
}
.ui-input-text
{
height: 25px !important;
}
textarea.ui-input-text
{
    height:100px !important;
}
#wait {
		position: fixed;
		opacity: 0;
		left: 20%;
		top: 30px;
		font-family: garamond, arial, sans-serif;
		font-weight: bold;
		font-size:30px;
		text-shadow: 2px 5px 20px #000000;
		color:#000000;
}

</style>
</head>

<body>


<div data-role="page" class="wrapper" id="main">

	<header data-role="header">
	<p align="center"><b><font size="5"><image src="images/logo_j.jpg">
	Eventcast</font></b>
	<br>
    <font size="2">Post your Meetup to the World</font>
	</p>
	</header>
  <h2 style="text-align:center">Post a Meetup</h2>

 <ul data-role="listview">
 <li>

 <form method="get" enctype="multipart/form-data"
    name="castform" id="castformid" action="/submit">
	<H2>
		<label for='group'>Choose Group: </label>
    <select id="select-choice-1">
       <%= options_for_select( @events.reverse ) %>
    </select>
	<br>
		<H2><label for='title'>Title:</label>
		<input type="text" placeholder="Our Next Event" name="title">
	<br>
    <label for='group'>Choose Place: </label>
    <select id="select-choice-2">
       <%= options_for_select( @places ) %>
    </select>
		<label for="dater">Date:</label>
		<input type="date" name="date" id="date" value=""  />
	<br>
		<label for='title'>Start Time:</label>
		<input type="time" name="time1">
	<br>
		<label for='title'>End Time:</label>
		<input type="time" name="time2">
	<br>
		<label for='descp'>Description:</label>
		<textarea cols="40" rows="10" name="desc" id="desc" placeholder="Your event description..."></textarea>
	<br>
		<label for='msg1'>Invite Message:</label>
		<input id="msg01" placeholder="Place your invite message here!" name="msg01"></H2>
	<br>
		<div data-role="fieldcontain">
 	<fieldset data-role="controlgroup" data-type="horizontal">
		<H2><legend>Media to Share:</legend></H2>
		<input type="checkbox" name="checkbox-1" id="checkbox-1" class="custom" />
		<label for="checkbox-1"><img src="images/facebook.jpg"></label>
		<input type="checkbox" name="checkbox-2" id="checkbox-2" class="custom" />
		<label for="checkbox-2"><img src="images/twitter.jpg"></label>
		<input type="checkbox" name="checkbox-3" id="checkbox-3" class="custom" />
		<label for="checkbox-3"><img src="images/weibo.jpg"></label>
		<input type="checkbox" name="checkbox-4" id="checkbox-4" class="custom" />
		<label for="checkbox-4"><img src="images/mailchimp.jpg"></label>
    </fieldset>
		</div>
	<input id="submitbtn" type="submit" value="Schedule it" onclick="castgo();">
</form>
 </p>
</li>
	</ul>
<script type="text/javascript">
function waitfunc()
{
  document.getElementById('wait').style.opacity="0.8";
}

function castgo(){
  $("#castformid").submit(function(e)
  {
      var postData = $(this).serializeArray();
      var formURL = $(this).attr("action");
      $.ajax(
      {
          url : formURL,
          type: "POST",
          data : postData,
          success:function(data, textStatus, jqXHR)
          {
              window.location.href = '/thanks';
          },
          error: function(jqXHR, textStatus, errorThrown)
          {
              //if fails
          }
      });
      e.preventDefault(); //STOP default action
      e.unbind(); //unbind. to stop multiple form submit.
  });
}
</script>
	  <div>
	  <footer data-role="footer">
	  <nav data-role="navbar">
	  <p align="center">
    <img border="0" src="images/loudspeakwave.gif">
	  <br>
	  </p>
	</footer>
</div>

</body>

</html>

app/views/casts/thanks.html.erb
<!doctype html>
<html lang="en" manifest="cache.manifest">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="description" content="post meetup, tweet meetup">
<meta name="keywords" content="post meetup, tweet meetup, post on facebook, meetup on FB">
<title>Eventcast</title>

		<script>
  //reset type=date inputs to text
  $( document ).bind( "mobileinit", function(){
    $.mobile.page.prototype.options.degradeInputs.date = true;
  });
</script>


<link rel="stylesheet" href="http://code.jquery.com/mobile/1.1.1/
	jquery.mobile-1.1.1.min.css"/>
	<script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
	<script src="http://code.jquery.com/mobile/1.1.1/jquery.mobile-1.1.1.min.js"></script>

	<meta name="viewport" content="width-device-width,
	initial-scale=1, maximum-scale=1" />






<style>

body {
		background:#2E2E2E;
		    }

.centerblock {
	position:absolute;
    width: 300px;}

a
{
    text-decoration:none !important;
    font-family:helvetica !important;
    color:white !important;
	text-shadow:0 0 0;
    background:red !important;
}
.ui-input-text
{
height: 25px !important;
}
textarea.ui-input-text
{
    height:100px !important;
}


</style>






</head>

<body>


<div data-role="page" class="wrapper" id="main">

	<header data-role="header">
	<p align="center"><b><font size="5"><image src="/images/logo_j.jpg">
	<br>Eventcast</font></b>
	<br>
    <font size="2">Post your Meetup to the World</font>
	</p>
	</header>



<p></p>



 <ul data-role="listview" align="center">
 <image src="images/thankyou.gif">
 <h2><p><li>Great, your event has been posted<br>
 and broadcasted.<br>
 Thank you for using Eventcast.</p></h2>
 </li>
 </p>

 	<a href="/castout" data-role="button" type="launchbutton" name='applaunch'>Post another event</a>

 </ul>










</body>

</html>

app/views/casts/welcome.html.erb
<!doctype html>
<html lang="en" manifest="cache.manifest">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="description" content="post meetup, tweet meetup">
<meta name="keywords" content="post meetup, tweet meetup, post on facebook, meetup on FB">
<title>Eventcast</title>

		<script>
  //reset type=date inputs to text
  $( document ).bind( "mobileinit", function(){
    $.mobile.page.prototype.options.degradeInputs.date = true;
  });
</script>


<link rel="stylesheet" href="http://code.jquery.com/mobile/1.1.1/
	jquery.mobile-1.1.1.min.css"/>
	<script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
	<script src="http://code.jquery.com/mobile/1.1.1/jquery.mobile-1.1.1.min.js"></script>

	<meta name="viewport" content="width-device-width,
	initial-scale=1, maximum-scale=1" />
<style>

body {
		background:#2E2E2E;
		    }

.centerblock {
	position:absolute;
    width: 300px;}

a
{
    text-decoration:none !important;
    font-family:helvetica !important;
    color:white !important;
	text-shadow:0 0 0;
    background:red !important;
	left: 2px;
	width: 49%;
	padding: 2px;
}
.ui-input-text
{
height: 25px !important;
}
textarea.ui-input-text
{
    height:100px !important;
}


</style>






</head>

<body>


<div data-role="page" class="wrapper" id="main">

	<header data-role="header">
	<p align="center"><b><font size="5"><image src="images/logo_j.jpg">
	<br>Eventcast</font></b>
	<br>
    <font size="2">Post your Meetup to the World</font>
	</p>
	</header>
<p></p>
 <ul data-role="listview" align="center">
 <image src="images/welcomepic.gif">
 <h2><p><li>Welcome to Eventcast<br>
 Schedule a meetup and <br>
 broadcast it to social media<br>
 instantly!</p></h2>
 </li>
 </p>
<hr>
  	<fieldset data-role="controlgroup" data-type="horizontal">
	<a href="/login" data-role="button" name='toindex'>Log In</a>
	<a href="/users/sign_up" data-role="button" name='toregister'>Register</a>
	</fieldset>

 </ul>










</body>

</html>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "EventCast" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "EventCast" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <!--  <%= render 'layouts/navigation' %> -->
  <p align="center"><b><font size="5"><image src="../images/logo_j.jpg">
	EventCast</font></b>
	<br>
    <font size="2">Post your Meetup to the World</font>
	</p>

    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>